# Generated by Django 2.2 on 2021-05-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
