# Generated by Django 2.2 on 2021-05-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_paymentdetails_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='payment_status',
        ),
    ]
