# Generated by Django 2.2 on 2021-05-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_remove_paymentdetails_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
