# Generated by Django 2.2 on 2021-05-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_paymentdetails_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
