# Generated by Django 2.2 on 2021-05-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0010_usercourse_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='payment',
        ),
    ]
